# Generated by Django 3.0.2 on 2020-02-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200213_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='more',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
